### ISSUE TITLE
Quantitive results on the underwater image enhancement task

### ISSUE THREAD

**Issue by zzzack66** [zkawfanx/Atlantis#1]
Hi there，
Thank you for your awesome work.
Can you please quantitive results on the underwater image enhancement task?

**Comment by zkawfanx** [comment]
Hi,
Thank you for your interest in our work.

Sorry but we did not perform quantitative evaluation since it is not the main focus in this work. The UIE results were obtained directly from Sea-thru algorithm and only used to show the feasibility of our depth estimates on downstream applications. You can refer to [Sea-thru paper](https://openaccess.thecvf.com/content_CVPR_2019/papers/Akkaynak_Sea-Thru_A_Method_for_Removing_Water_From_Underwater_Images_CVPR_2019_paper.pdf) for more details.

**Comment by zzzack66** [comment]
Thank you for your reply.
